In [1]:
from sklearn.feature_extraction.text import CountVectorizer
docs = ['this this this book',
        'this cat good',
        'cat good shit']

In [87]:
def count(docs):
    count_model = CountVectorizer(ngram_range=(1,1))
    X = count_model.fit_transform(docs)
    Xc = (X.T * X)
    print (Xc.shape)
    print(count_model.get_feature_names())
    print(Xc.todense())
    
    

In [86]:
count_model = CountVectorizer(ngram_range=(1,1))

In [3]:
X = count_model.fit_transform(docs)
Xc = (X.T * X)
print(Xc.todense())

[[ 1  0  0  0  0  0  3  1  0  2]
 [ 0  2  2  2  1  1  1  0  1  0]
 [ 0  2  2  2  1  1  1  0  1  0]
 [ 0  2  2  2  1  1  1  0  1  0]
 [ 0  1  1  1  1  1  0  0  0  0]
 [ 0  1  1  1  1  1  0  0  0  0]
 [ 3  1  1  1  0  0 10  3  1  6]
 [ 1  0  0  0  0  0  3  1  0  2]
 [ 0  1  1  1  0  0  1  0  1  0]
 [ 2  0  0  0  0  0  6  2  0  4]]


In [54]:
import re
trails = ['Ram','1','shyam','hari']

# \b means word boundaries.
regex = r"\b(?:{})\b".format("|".join(trails))

s = "Ram is number 1 than hari"

res = re.split(regex, s)

In [55]:
print(res)

['', ' is number ', ' than ', '']


In [56]:
import os
import stopwords
import re
import pandas as pd
import nltk
from nltk import word_tokenize
stopwords = open("stopwords.txt").read().splitlines()
def loadData(loc):
        BASEDIR=os.path.dirname(os.path.realpath('__file__'))
        df=pd.read_csv(BASEDIR+loc,names=["headline","news"])
        return df


In [57]:
import numpy as np

In [58]:
df=loadData("/dataset/onlineKhabar.csv")
REPLACE_BY_SPACE_RE = re.compile('[?!/(){}\[\]\|@,;\'\']')
def removeCharacs(text):
    text=re.sub(REPLACE_BY_SPACE_RE,' ',text)# replace REPLACE_BY_SPACE_RE symbols by space in text
    return text

In [59]:
flatten = lambda x : ''.join(x.split('\','))

In [60]:
df['news'] = df['news'].map(flatten).map(removeCharacs)


In [61]:
def stem_text_cat2(text):
    return re.sub('(मा|को|ले|बाट|का|हरु|हरुसँग|सँग|लाई|हरू|हरूसँग|हरू)','',text)
allwords = open("dict.txt").read().splitlines()
suffixes = ('ी' , 'ीया' ,  'ीय' ,'े' , 'नु' , 'दै' , 'ेको' , 'ै')
def stem_text_cat1(word):
    if word.endswith(suffixes):
        wordlist =  [word.rstrip(x) for x in suffixes]
        for i in wordlist:
            if i!= word:
                if i in allwords:
                    return i
                    
        
    return word
    

In [62]:
def stemming(text):
    text =  ' '.join([stem_text_cat1(a) for a in word_tokenize(text)])
    return ' '.join([stem_text_cat2(a) for a in word_tokenize(text)])
    
    

In [63]:
df['news'] = df['news'].map(stemming)

In [64]:
def sent_tokenize(text):
    sentence = [x for x in text.split('।')] 
    return sentence
df['news-ws']=df['news'].map(sent_tokenize)

In [65]:
# function to remove stopwords
def remove_stopword(sen):
    sen_new = " ".join([i for i in sen if i not in stopwords])
    return sen_new
remove_stopwords = lambda sent : [remove_stopword(r.split()) for r in sent]


In [66]:
df['news-ws'] = df['news-ws'].map(remove_stopwords)

In [76]:
df['news-ws'][1]

['विश्व नम्वर वान टेक कम्पनी एप्पल निस प्रमुख र्यरी अधिकृत सिइओ पाउन तलब भत्ता चानचुने कुरै',
 'त्यसै एप्पल वर्तन सिइओ टिम कुक गत वर्ष सन् २०१५ १ अर्ब रुपैयाँ बढि वाषिर्क तलबभत्ता बुझे',
 'अघिल्लो वर्ष तुलना सन् २०१५ कुक तलब भत्ता ११.५ प्रतिशत वृद्धि',
 'उन वर्ष एप्पल १ करोड ३ डलर रकम बुझे',
 'कुक आधारभुत बेतन गत वर्ष १४.४ प्रतिशत २० करोड रुपैयाँ वृद्धि नन इक्विटी इन्सेन्टिभ १९ प्रतिशत वृद्धि ८० करोड रुपैयाँ पुगे',
 'यतिधेरै तलब भत्ता थाप्न कुक एप्पल एकत्र कर्मचारी होलान् कर्मचारी तलब उन निक भन्न सोँच्नुहोला',
 'अचम्म एप्पल उच्च पदस्थ र्यरीमध्ये कुक पाए तलब भत्ता सबैभन्दा',
 'कम्पनी प्रमुख वित्तिय अधिकृत लू वाषिर्क तलब ८१ प्रतिशत वृद्धि उन गत वर्ष अढाइ अर्ब रुपैयाँ बढि तलब भत्ता बुझे',
 'रिटेल एण्ड अनलाइन स्टोर वरिष्ठ उपाध्यक्ष एन्जेला गत वर्ष एप्पल सबैभन्दा बढि तलब भत्ता बुझ्ने कर्मचारी',
 'उन गत वर्ष उन २ अर्ब ६० करोड रुपैयाँ बढि तलब भत्ता बुझेकी छिन्',
 'गत वर्ष सन् २०१५ एप्पलल बिक्रि २८ प्रतिशत बढ्यो मुनाफा ३५ प्रतिशत बढे बताइए',
 'सन् २००८ यता पहिलोपटक एप्पलल शेयर मूल्य गिरावट',
 

In [88]:
count(["विश्व नम्वर","उन वर्ष","यता पहिलोपटक"])

(6, 6)
['उन', 'नम', 'पटक', 'पह', 'यत', 'वर']
[[1 0 0 0 0 1]
 [0 1 0 0 0 1]
 [0 0 1 1 1 0]
 [0 0 1 1 1 0]
 [0 0 1 1 1 0]
 [1 1 0 0 0 2]]


In [68]:
def findCandidates(text):
    clusters=[]
    word1=[]
    for word in word_tokenize(text):
        if word in stopwords:
            clusters.append(word1)
            word1 =[]
            continue
        else:
            word1.append(word)
    return [' '.join(a).replace('।','') for a in clusters if len(a)>1]        

In [69]:
df['kW-candidates'] = df['news'].map(findCandidates)