In [243]:
from sklearn.feature_extraction.text import CountVectorizer
docs = ['this this this book',
        'this cat good',
        'cat good shit']

In [244]:
def count(docs):
    count_model = CountVectorizer(ngram_range=(1,1))
    X = count_model.fit_transform(docs)
    Xc = (X.T * X)
    print (Xc.shape)
    print(count_model.get_feature_names())
    print(Xc.todense())
    
    

In [245]:
count_model = CountVectorizer(ngram_range=(1,1))

In [246]:
X = count_model.fit_transform(docs)
Xc = (X.T * X)
print(Xc.todense())

[[ 1  0  0  0  3]
 [ 0  2  2  1  1]
 [ 0  2  2  1  1]
 [ 0  1  1  1  0]
 [ 3  1  1  0 10]]


In [247]:
import re
trails = ['Ram','1','shyam','hari']

# \b means word boundaries.
regex = r"\b(?:{})\b".format("|".join(trails))

s = "Ram is number 1 than hari"

res = re.split(regex, s)

In [248]:
print(res)

['', ' is number ', ' than ', '']


In [249]:
import os
import stopwords
import re
import pandas as pd
import nltk
from nltk import word_tokenize
stopwords = open("stopwords.txt").read().splitlines()
def loadData(loc):
        BASEDIR=os.path.dirname(os.path.realpath('__file__'))
        df=pd.read_csv(BASEDIR+loc,names=["headline","news"])
        return df


In [250]:
import numpy as np

In [251]:
df=loadData("/dataset/onlineKhabar.csv")
REPLACE_BY_SPACE_RE = re.compile('[?!/(){}\[\]\|@,;\'\']')
def removeCharacs(text):
    text=re.sub(REPLACE_BY_SPACE_RE,' ',text)# replace REPLACE_BY_SPACE_RE symbols by space in text
    return text

In [252]:
flatten = lambda x : ''.join(x.split('\','))

In [253]:
df['news'] = df['news'].map(flatten).map(removeCharacs)


In [254]:
def stem_text_cat2(text):
    return re.sub('(मा|को|ले|बाट|का|हरु|हरुसँग|सँग|लाई|हरू|हरूसँग|हरू)','',text)
allwords = open("dict.txt").read().splitlines()
suffixes = ('ी' , 'ीया' ,  'ीय' ,'े' , 'नु' , 'दै' , 'ेको' , 'ै')
def stem_text_cat1(word):
    if word.endswith(suffixes):
        wordlist =  [word.rstrip(x) for x in suffixes]
        for i in wordlist:
            if i!= word:
                if i in allwords:
                    return i
                    
        
    return word
    

In [255]:
def stemming(text):
    text =  ' '.join([stem_text_cat1(a) for a in word_tokenize(text)])
    return ' '.join([stem_text_cat2(a) for a in word_tokenize(text)])
    


In [256]:
df['news'] = df['news'].map(stemming)

In [257]:
def sent_tokenize(text):
    sentence = [x for x in text.split('।')] 
    return sentence
df['news-ws']=df['news'].map(sent_tokenize)

In [258]:
def check(x):
    try:
        if isinstance(float(x), float):
            return False
    except:
        return True


In [259]:
# function to remove stopwords
def remove_stopword(sen):
    sen_new = " ".join([i for i in sen if i not in stopwords and check(i)])
    return sen_new
remove_stopwords = lambda sent : [remove_stopword(r.split()) for r in sent]


In [260]:
df['news-ws'] = df['news-ws'].map(remove_stopwords)

In [261]:
df['news-ws'][0]

['विश्व नम्वर वान टेक कम्पनी एप्पल निस प्रमुख र्यरी अधिकृत सिइओ पाउन तलब भत्ता चानचुने कुरै',
 'त्यसै एप्पल वर्तन सिइओ टिम कुक गत वर्ष सन् अर्ब रुपैयाँ बढि वाषिर्क तलबभत्ता बुझे',
 'अघिल्लो वर्ष तुलना सन् कुक तलब भत्ता प्रतिशत वृद्धि',
 'उन वर्ष एप्पल करोड डलर रकम बुझे',
 'कुक आधारभुत बेतन गत वर्ष प्रतिशत करोड रुपैयाँ वृद्धि नन इक्विटी इन्सेन्टिभ प्रतिशत वृद्धि करोड रुपैयाँ पुगे',
 'यतिधेरै तलब भत्ता थाप्न कुक एप्पल एकत्र कर्मचारी होलान् कर्मचारी तलब उन निक भन्न सोँच्नुहोला',
 'अचम्म एप्पल उच्च पदस्थ र्यरीमध्ये कुक पाए तलब भत्ता सबैभन्दा',
 'कम्पनी प्रमुख वित्तिय अधिकृत लू वाषिर्क तलब प्रतिशत वृद्धि उन गत वर्ष अढाइ अर्ब रुपैयाँ बढि तलब भत्ता बुझे',
 'रिटेल एण्ड अनलाइन स्टोर वरिष्ठ उपाध्यक्ष एन्जेला गत वर्ष एप्पल सबैभन्दा बढि तलब भत्ता बुझ्ने कर्मचारी',
 'उन गत वर्ष उन अर्ब करोड रुपैयाँ बढि तलब भत्ता बुझेकी छिन्',
 'गत वर्ष सन् एप्पलल बिक्रि प्रतिशत बढ्यो मुनाफा प्रतिशत बढे बताइए',
 'सन् यता पहिलोपटक एप्पलल शेयर मूल्य गिरावट',
 '']

In [262]:
from nltk import word_tokenize

In [263]:
vocab = set([x for x in ' '.join(df['news-ws'][0]).split(' ') ])
vocab = list(vocab)
vocab

['',
 'थाप्न',
 'एप्पल',
 'डलर',
 'एकत्र',
 'अचम्म',
 'एण्ड',
 'वृद्धि',
 'कम्पनी',
 'उच्च',
 'र्यरी',
 'सिइओ',
 'उन',
 'अघिल्लो',
 'वान',
 'त्यसै',
 'आधारभुत',
 'विश्व',
 'निक',
 'कुरै',
 'भत्ता',
 'वर्ष',
 'रुपैयाँ',
 'सोँच्नुहोला',
 'अढाइ',
 'बुझ्ने',
 'चानचुने',
 'यतिधेरै',
 'रिटेल',
 'वित्तिय',
 'उपाध्यक्ष',
 'बेतन',
 'बिक्रि',
 'गिरावट',
 'रकम',
 'एन्जेला',
 'लू',
 'बुझे',
 'पहिलोपटक',
 'यता',
 'तलब',
 'करोड',
 'सन्',
 'कर्मचारी',
 'एप्पलल',
 'बढ्यो',
 'अधिकृत',
 'प्रमुख',
 'निस',
 'नन',
 'होलान्',
 'र्यरीमध्ये',
 'अनलाइन',
 'पाए',
 'अर्ब',
 'तलबभत्ता',
 'नम्वर',
 'टेक',
 'तुलना',
 'बुझेकी',
 'कुक',
 'सबैभन्दा',
 'वरिष्ठ',
 'पुगे',
 'गत',
 'मुनाफा',
 'बढे',
 'शेयर',
 'मूल्य',
 'इक्विटी',
 'पदस्थ',
 'इन्सेन्टिभ',
 'भन्न',
 'पाउन',
 'वर्तन',
 'प्रतिशत',
 'बढि',
 'स्टोर',
 'छिन्',
 'बताइए',
 'वाषिर्क',
 'टिम']

In [291]:
document = [checkNum((word_tokenize(x))) for x in df['news-ws'][0]]


In [295]:
from collections import OrderedDict
names = vocab
occurrences = OrderedDict((name, OrderedDict((name, 0) for name in names)) for name in names)

# Find the co-occurrences:
for l in document:
    for i in range(len(l)):
        for item in l[:i] + l[i + 1:]:
            occurrences[l[i]][item] += 1
'''
# Print the matrix:
print(' ', ' '.join(occurrences.keys()))
for name, values in occurrences.items():
    print(name, ' '.join(str(i) for i in values.values()))'''

"\n# Print the matrix:\nprint(' ', ' '.join(occurrences.keys()))\nfor name, values in occurrences.items():\n    print(name, ' '.join(str(i) for i in values.values()))"

In [267]:
rows = ['deg','freq','deg/freq']
word_scores = OrderedDict((name, OrderedDict((r, 0) for r in rows)) for name in names)

In [268]:
for key in word_scores.keys():
    word_scores[key]['deg'] = sum(occurrences[key].values())
    word_scores[key]['freq'] = len([x for x in occurrences[key].values() if x!=0])
    if word_scores[key]['freq']!=0:
        word_scores[key]['deg/freq'] = word_scores[key]['deg']/word_scores[key]['freq']
    else:
        word_scores[key]['deg/freq']= 0

In [280]:
def checkMe(x):
    try:
        if isinstance(float(x), float):
            return True
    except:
        return False


In [281]:
def findCandidates(text):
    clusters=[]
    word1=[]
    for word in word_tokenize(text):
        if (word in stopwords) or checkMe(word):
            clusters.append(word1)
            word1 =[]
            continue
        else:
            word1.append(word)
    return [' '.join(a).replace('।','') for a in clusters if len(a)>1]        

In [282]:
df['kW-candidates'] = df['news'].map(findCandidates)

In [284]:
df['kW-candidates'][0]

['विश्व नम्वर वान टेक कम्पनी एप्पल',
 'प्रमुख र्यरी अधिकृत सिइओ पाउन तलब भत्ता चानचुने',
 ' त्यसै एप्पल वर्तन सिइओ टिम कुक गत वर्ष सन्',
 'अर्ब रुपैयाँ',
 'बढि वाषिर्क तलबभत्ता बुझे',
 ' अघिल्लो वर्ष तुलना सन्',
 'कुक तलब भत्ता',
 'प्रतिशत वृद्धि',
 'वर्ष एप्पल',
 'डलर रकम बुझे',
 ' कुक आधारभुत बेतन गत वर्ष',
 'करोड रुपैयाँ वृद्धि',
 'नन इक्विटी इन्सेन्टिभ',
 'प्रतिशत वृद्धि',
 'करोड रुपैयाँ पुगे',
 'यतिधेरै तलब भत्ता थाप्न कुक एप्पल एकत्र कर्मचारी होलान्',
 'कर्मचारी तलब उन',
 'भन्न सोँच्नुहोला ',
 'एप्पल उच्च पदस्थ र्यरीमध्ये कुक पाए तलब भत्ता सबैभन्दा',
 ' कम्पनी प्रमुख वित्तिय अधिकृत लू वाषिर्क तलब',
 'प्रतिशत वृद्धि',
 'उन गत वर्ष अढाइ अर्ब रुपैयाँ',
 'बढि तलब भत्ता बुझे',
 ' रिटेल एण्ड अनलाइन स्टोर वरिष्ठ उपाध्यक्ष एन्जेला गत वर्ष एप्पल सबैभन्दा बढि तलब भत्ता बुझ्ने कर्मचारी',
 ' उन गत वर्ष उन',
 'करोड रुपैयाँ',
 'बढि तलब भत्ता बुझेकी छिन्  गत वर्ष सन्',
 'एप्पलल बिक्रि',
 'प्रतिशत बढ्यो',
 'प्रतिशत बढे बताइए',
 'यता पहिलोपटक एप्पलल शेयर मूल्य']

In [287]:
scoredCandidates = []
for sent in df['kW-candidates'][0]:
    sumis=0
    for word in word_tokenize(sent):
        sumis += word_scores[word]['deg/freq']
    scoredCandidates.append((sent,sumis/len(word_tokenize(sent))))

In [296]:
sorted(list(set(scoredCandidates)), key = lambda x : x[1],reverse=True)

[('प्रतिशत वृद्धि', 2.1142857142857143),
 ('करोड रुपैयाँ', 2.0922619047619047),
 ('करोड रुपैयाँ वृद्धि', 2.0615079365079363),
 ('कर्मचारी तलब उन', 1.880543364681296),
 ('अर्ब रुपैयाँ', 1.8392857142857144),
 ('करोड रुपैयाँ पुगे', 1.8392857142857142),
 (' उन गत वर्ष उन', 1.7827946127946128),
 ('कुक तलब भत्ता', 1.7115921988880245),
 ('उन गत वर्ष अढाइ अर्ब रुपैयाँ', 1.6750652651633045),
 ('प्रतिशत बढ्यो', 1.66984126984127),
 ('बढि तलब भत्ता बुझे', 1.6414635727249158),
 ('वर्ष एप्पल', 1.5833333333333335),
 (' कुक आधारभुत बेतन गत वर्ष', 1.5227724867724866),
 ('बढि तलब भत्ता बुझेकी छिन्  गत वर्ष सन्', 1.5161665875230654),
 ('प्रतिशत बढे बताइए', 1.4835978835978836),
 ('यतिधेरै तलब भत्ता थाप्न कुक एप्पल एकत्र कर्मचारी होलान्',
  1.430366123909177),
 ('नन इक्विटी इन्सेन्टिभ', 1.3333333333333333),
 (' रिटेल एण्ड अनलाइन स्टोर वरिष्ठ उपाध्यक्ष एन्जेला गत वर्ष एप्पल सबैभन्दा बढि तलब भत्ता बुझ्ने कर्मचारी',
  1.3073897027050383),
 ('एप्पल उच्च पदस्थ र्यरीमध्ये कुक पाए तलब भत्ता सबैभन्दा',
  1.2921650