In [1]:
from sklearn.feature_extraction.text import CountVectorizer
docs = ['this this this book',
        'this cat good',
        'cat good shit']

In [2]:
def count(docs):
    count_model = CountVectorizer(ngram_range=(1,1))
    X = count_model.fit_transform(docs)
    Xc = (X.T * X)
    print (Xc.shape)
    print(count_model.get_feature_names())
    print(Xc.todense())
    
    

In [3]:
count_model = CountVectorizer(ngram_range=(1,1))

In [4]:
X = count_model.fit_transform(docs)
Xc = (X.T * X)
print(Xc.todense())

[[ 1  0  0  0  3]
 [ 0  2  2  1  1]
 [ 0  2  2  1  1]
 [ 0  1  1  1  0]
 [ 3  1  1  0 10]]


In [5]:
import re
trails = ['Ram','1','shyam','hari']

# \b means word boundaries.
regex = r"\b(?:{})\b".format("|".join(trails))

s = "Ram is number 1 than hari"

res = re.split(regex, s)

In [6]:
print(res)

['', ' is number ', ' than ', '']


In [13]:
import os
import re
import pandas as pd
import nltk
from nltk import word_tokenize
stopwords = open("listfile.txt").read().splitlines()
def loadData(loc):
        BASEDIR=os.path.dirname(os.path.realpath('__file__'))
        df=pd.read_csv(BASEDIR+loc,names=["headline","news"])
        return df


In [18]:
import numpy as np

In [19]:
df=loadData("/dataset/onlineKhabar.csv")
REPLACE_BY_SPACE_RE = re.compile('[?!/(){}\[\]\|@,;\'\']')
def removeCharacs(text):
    text=re.sub(REPLACE_BY_SPACE_RE,' ',text)# replace REPLACE_BY_SPACE_RE symbols by space in text
    return text

In [20]:
flatten = lambda x : ''.join(x.split('\','))

In [21]:
df['news'] = df['news'].map(flatten).map(removeCharacs)


In [22]:
def stem_text_cat2(text):
    return re.sub('(मा|को|ले|बाट|का|हरु|हरुसँग|सँग|लाई|हरू|हरूसँग|हरू|पटक)','',text)
allwords = open("dict.txt").read().splitlines()
suffixes = ('ी' , 'ीया' ,  'ीय' ,'े' , 'नु' , 'दै' , 'ेको' , 'ै','कै')
def stem_text_cat1(word):
    if word.endswith(suffixes):
        wordlist =  [word.rstrip(x) for x in suffixes]
        for i in wordlist:
            if i!= word:
                if i in allwords:
                    return i
                    
        
    return word
    

In [23]:
def stemming(text):
    text =  ' '.join([stem_text_cat1(a) for a in word_tokenize(text)])
    return ' '.join([stem_text_cat2(a) for a in word_tokenize(text)])
    


In [24]:
df['news'] = df['news'].map(stemming)

In [25]:
def sent_tokenize(text):
    sentence = [x for x in text.split('।')] 
    return sentence
df['news-ws']=df['news'].map(sent_tokenize)

In [26]:
def check(x):
    try:
        if isinstance(float(x), float):
            return False
    except:
        return True


In [27]:
# function to remove stopwords
def remove_stopword(sen):
    sen_new = " ".join([i for i in sen if i not in stopwords and check(i)])
    return sen_new
remove_stopwords = lambda sent : [remove_stopword(r.split()) for r in sent]


In [28]:
df['news-ws'] = df['news-ws'].map(remove_stopwords)

In [29]:
df['news-ws'][0]

['विश्व नम्वर वान टेक कम्पनी एप्पल निस प्रमुख र्यरी अधिकृत सिइओ पाउन तलब भत्ता चानचुने कुरै',
 'एप्पल वर्तन सिइओ टिम कुक गत वर्ष सन् अर्ब रुपैयाँ बढि वाषिर्क तलबभत्ता बुझे',
 'अघिल्लो वर्ष तुलना सन् कुक तलब भत्ता प्रतिशत वृद्धि',
 'वर्ष एप्पल करोड डलर रकम बुझे',
 'कुक आधारभुत बेतन गत वर्ष प्रतिशत करोड रुपैयाँ वृद्धि नन इक्विटी इन्सेन्टिभ प्रतिशत वृद्धि करोड रुपैयाँ पुगे',
 'यतिधेरै तलब भत्ता थाप्न कुक एप्पल एकत्र कर्मचारी होलान् कर्मचारी तलब निक सोँच्नुहोला',
 'अचम्म एप्पल उच्च पदस्थ र्यरीमध्ये कुक पाए तलब भत्ता सबैभन्दा',
 'कम्पनी प्रमुख वित्तिय अधिकृत लू वाषिर्क तलब प्रतिशत वृद्धि गत वर्ष अढाइ अर्ब रुपैयाँ बढि तलब भत्ता बुझे',
 'रिटेल एण्ड अनलाइन स्टोर वरिष्ठ उपाध्यक्ष एन्जेला गत वर्ष एप्पल सबैभन्दा बढि तलब भत्ता बुझ्ने कर्मचारी',
 'गत वर्ष अर्ब करोड रुपैयाँ बढि तलब भत्ता बुझेकी',
 'गत वर्ष सन् एप्पलल बिक्रि प्रतिशत बढ्यो मुनाफा प्रतिशत बढे बताइए',
 'सन् एप्पलल शेयर मूल्य गिरावट',
 '']

In [30]:
from nltk import word_tokenize

In [42]:
def checkMe(x):
    try:
        if isinstance(float(x), float):
            return True
    except:
        return False
def checkNum(x):
    try:
        if isinstance(float(x), float):
            return 
    except:
        return x

def findCandidates(text):
    clusters=[]
    word1=[]
    for word in word_tokenize(text):
        if (word in stopwords) or checkMe(word):
            clusters.append(word1)
            word1 =[]
            continue
        else:
            word1.append(word)
    return [' '.join(a).replace('।','') for a in clusters if len(a)>1]
df['kW-candidates'] = df['news'].map(findCandidates)

In [43]:
document = [checkNum((word_tokenize(x))) for x in df['kW-candidates'][19]]

In [44]:
from collections import OrderedDict
names = vocab
occurrences = OrderedDict((name, OrderedDict((name, 0) for name in names)) for name in names)

# Find the co-occurrences:
for l in document:
    for i in range(len(l)):
        for item in l[:i] + l[i + 1:]:
            occurrences[l[i]][item] += 1
'''
# Print the matrix:
print(' ', ' '.join(occurrences.keys()))
for name, values in occurrences.items():
    print(name, ' '.join(str(i) for i in values.values()))'''

"\n# Print the matrix:\nprint(' ', ' '.join(occurrences.keys()))\nfor name, values in occurrences.items():\n    print(name, ' '.join(str(i) for i in values.values()))"

In [45]:
rows = ['deg','freq','deg/freq']
word_scores = OrderedDict((name, OrderedDict((r, 0) for r in rows)) for name in names)

In [46]:
for key in word_scores.keys():
    word_scores[key]['deg'] = sum(occurrences[key].values())
    word_scores[key]['freq'] = len([x for x in occurrences[key].values() if x!=0])
    if word_scores[key]['freq']!=0:
        word_scores[key]['deg/freq'] = word_scores[key]['deg']/word_scores[key]['freq']
    else:
        word_scores[key]['deg/freq']= 0

In [47]:
def checkMe(x):
    try:
        if isinstance(float(x), float):
            return True
    except:
        return False


In [48]:
df['kW-candidates'] = df['news'].map(findCandidates)

In [49]:
# find word co-occurrence graph on candidate keywords 

In [50]:
df['kW-candidates'][19]

['इक्रोब्लगिंग साइट टि्वटर टि्वट्स',
 'क्यारेक्टर्स सी बढाएर छिटै',
 ' प्रविधि सम्बन्ध',
 'सचार साइट रिपोर्ट',
 'क्यारेक्टर्स सी तय भएै प्रयोगकर्ता शव्द',
 'विभिन्न चिन्ह ै',
 'बढि शव्द टि्वट',
 ' टि्वटर',
 'फिचर ठ्याक्कै',
 'आगामी र्च महिनासम्म सी बढाएर',
 'अक्षर पूराउने विषय टि्वटर',
 ' परीक्षण रुप टि्वटर क्यारेक्टर्स लिमिट',
 'फिचर लन्च गर्नसक्ने अनुन गरिए',
 ' टि्वटर सहसस्थापक',
 'सिइओ ज्याक डोर्सी',
 'की प्रयोगकर्ता',
 'अक्षर सि रण टि्वट ख्नु साटो',
 'साग्री स्क्रिनसट खिचेर टि्वटर',
 'बाध्यता प्रयोगकर्ता मुक्त',
 'निस अझ सुविधा प्रदान',
 'उत्कृष्ट बनाउन',
 ' प्रयोगकर्ता',
 ' सचार साइट Re Code',
 'टाइमलाइन लुक्स',
 'प्रयोगकर्ता टि्वट',
 'क्यारेक्टर्सकै अप्सन देखिनेछ',
 'टि्वट लम्बाउन',
 'अप्सन क्लिक गर्नुपर्नेछ',
 'लामो टि्वट ख्ने ठाउँ प्राप्त',
 'सिइओ डोर्सी नियुक्त भएै टि्वटर',
 'नयाँपन देखाउँदै',
 'टि्वटर Moments फिचर',
 ' पोल फिचर',
 'Buy बटन',
 'तारा आकृतिवाला “ avorite बटन',
 'मुटु आकृतिवाला Like बटन',
 ' गत मंगलबार',
 'टि्वटर प्रयोगकर्ता टि्वटर टि्वट लिमिट बढाउन दबाब',
 '# B

In [51]:
scoredCandidates = []
for sent in df['kW-candidates'][19]:
    sumis=0
    for word in word_tokenize(sent):
        sumis += word_scores[word]['deg/freq']
    scoredCandidates.append((sent,sumis/len(word_tokenize(sent))))

In [52]:
sorted(list(set(scoredCandidates)), key = lambda x : x[1],reverse=True)

[(' टि्वटर', 1.28),
 ('टि्वटर प्रयोगकर्ता टि्वटर टि्वट लिमिट बढाउन दबाब', 1.2116418875242405),
 (' प्रयोगकर्ता', 1.1538461538461537),
 (' टि्वटर सहसस्थापक', 1.1400000000000001),
 ('सिइओ डोर्सी नियुक्त भएै टि्वटर', 1.1360000000000001),
 ('प्रयोगकर्ता टि्वट', 1.1357466063348416),
 ('सिइओ ज्याक डोर्सी', 1.1333333333333335),
 ('सचार साइट रिपोर्ट', 1.130952380952381),
 (' परीक्षण रुप टि्वटर क्यारेक्टर्स लिमिट', 1.1241818181818182),
 ('क्यारेक्टर्स सी बढाएर छिटै', 1.1143939393939395),
 ('इक्रोब्लगिंग साइट टि्वटर टि्वट्स', 1.1057142857142856),
 (' सचार साइट Re Code', 1.0982142857142856),
 ('टि्वटर Moments फिचर', 1.0933333333333335),
 ('मुटु आकृतिवाला Like बटन', 1.0773809523809526),
 ('की प्रयोगकर्ता', 1.0769230769230769),
 ('क्यारेक्टर्स सी तय भएै प्रयोगकर्ता शव्द', 1.0741258741258741),
 ('आगामी र्च महिनासम्म सी बढाएर', 1.0733333333333335),
 ('Buy बटन', 1.0714285714285714),
 ('साग्री स्क्रिनसट खिचेर टि्वटर', 1.07),
 ('अक्षर पूराउने विषय टि्वटर', 1.07),
 ('तारा आकृतिवाला “ avorite बटन', 1.0619

In [39]:
गर्नेहो आफु चाहे पारेर चाहन्छन् भन्न गर्नेछैन  त्यसै रहँदै बढाएर 

SyntaxError: invalid syntax (<ipython-input-39-c2d452c85a1a>, line 1)

In [17]:
stopword = sorted(list( set(stopwords + ['हुँ' ,'पुगे','सबै','बुझे' 'बुझेकी',' होलान् ','पाए','गर्नेहो','गर्नेहोईन','आफु','चाहे','नचाहे','पारेर', 'गर्दछ','छिन्','सक्नेछन्' ,'रहँदै','चाहन्छन्','भन्न', 'यता' ,'गर्नेछैन', 'उन' ,'त्यसै','नआउन' , 'आउन' , 'यहीँ ','रहे' ,'नरहे','तयार' ,'गरिरहे',' बताइए ','कुनैपनि','हटाएर','दिँदै', 'जस' , 'सक्नुहुन्छ' ,'सक्नुहुन्न' ,'दिदैन' ,'गर्दैन' ,'नलिए', 'दिन्छ' , 'गर्दछ' , 'लिए' , 'हेर्न' , 'सकिने' ,'तपाइँ' ,'जुनसुकै'])))

In [18]:
with open('listfile.txt', 'w') as filehandle:  
    for listitem in stopword:
        filehandle.write('%s\n' % listitem)

In [19]:
 होलान् पाए सबैभन्दा

SyntaxError: invalid syntax (<ipython-input-19-89942c92ba65>, line 1)

In [21]:
'बुझेकी' in stopword

False

In [12]:
stopwords

[' बताइए ',
 ' होलान् ',
 'अक्सर',
 'अगाडि',
 'अगाडी',
 'अघि',
 'अझै',
 'अठार',
 'अथवा',
 'अनि',
 'अनुसार',
 'अन्तर्गत',
 'अन्य',
 'अन्यत्र',
 'अन्यथा',
 'अब',
 'अरु',
 'अरुलाई',
 'अरू',
 'अर्को',
 'अर्थात',
 'अर्थात्',
 'अलग',
 'अलि',
 'अवस्था',
 'अहिले',
 'आउन',
 'आए',
 'आएका',
 'आएको',
 'आज',
 'आजको',
 'आठ',
 'आत्म',
 'आदि',
 'आदिलाई',
 'आफनो',
 'आफु',
 'आफू',
 'आफूलाई',
 'आफै',
 'आफैँ',
 'आफ्नै',
 'आफ्नो',
 'आयो',
 'उ',
 'उक्त',
 'उदाहरण',
 'उन',
 'उनको',
 'उनलाई',
 'उनले',
 'उनि',
 'उनी',
 'उनीहरुको',
 'उन्नाइस',
 'उप',
 'उसको',
 'उसलाई',
 'उसले',
 'उहालाई',
 'ऊ',
 'एउटा',
 'एउटै',
 'एक',
 'एकदम',
 'एघार',
 'ओठ',
 'औ',
 'औं',
 'कता',
 'कति',
 'कतै',
 'कम',
 'कमसेकम',
 'कसरि',
 'कसरी',
 'कसै',
 'कसैको',
 'कसैलाई',
 'कसैले',
 'कसैसँग',
 'कस्तो',
 'कहाँबाट',
 'कहिलेकाहीं',
 'का',
 'काम',
 'कारण',
 'कि',
 'किन',
 'किनभने',
 'कुन',
 'कुनै',
 'कुनैपनि',
 'कुन्नी',
 'कुरा',
 'कृपया',
 'के',
 'केहि',
 'केही',
 'को',
 'कोहि',
 'कोहिपनि',
 'कोही',
 'कोहीपनि',
 'क्रमशः',
 'गए',
 'गएको',
 'गए