In [351]:
from sklearn.feature_extraction.text import CountVectorizer
docs = ['this this this book',
        'this cat good',
        'cat good shit']

In [352]:
def count(docs):
    count_model = CountVectorizer(ngram_range=(1,1))
    X = count_model.fit_transform(docs)
    Xc = (X.T * X)
    print (Xc.shape)
    print(count_model.get_feature_names())
    print(Xc.todense())
    
    

In [353]:
count_model = CountVectorizer(ngram_range=(1,1))

In [354]:
X = count_model.fit_transform(docs)
Xc = (X.T * X)
print(Xc.todense())

[[ 1  0  0  0  3]
 [ 0  2  2  1  1]
 [ 0  2  2  1  1]
 [ 0  1  1  1  0]
 [ 3  1  1  0 10]]


In [355]:
import re
trails = ['Ram','1','shyam','hari']

# \b means word boundaries.
regex = r"\b(?:{})\b".format("|".join(trails))

s = "Ram is number 1 than hari"

res = re.split(regex, s)

In [356]:
print(res)

['', ' is number ', ' than ', '']


In [369]:
import os
import stopwords
import re
import pandas as pd
import nltk
from nltk import word_tokenize
stopwords = open("stopwords.txt").read().splitlines()
def loadData(loc):
        BASEDIR=os.path.dirname(os.path.realpath('__file__'))
        df=pd.read_csv(BASEDIR+loc,names=["headline","news"])
        return df


In [370]:
import numpy as np

In [371]:
df=loadData("/dataset/onlineKhabar.csv")
REPLACE_BY_SPACE_RE = re.compile('[?!/(){}\[\]\|@,;\'\']')
def removeCharacs(text):
    text=re.sub(REPLACE_BY_SPACE_RE,' ',text)# replace REPLACE_BY_SPACE_RE symbols by space in text
    return text

In [372]:
flatten = lambda x : ''.join(x.split('\','))

In [373]:
df['news'] = df['news'].map(flatten).map(removeCharacs)


In [374]:
def stem_text_cat2(text):
    return re.sub('(मा|को|ले|बाट|का|हरु|हरुसँग|सँग|लाई|हरू|हरूसँग|हरू|पटक)','',text)
allwords = open("dict.txt").read().splitlines()
suffixes = ('ी' , 'ीया' ,  'ीय' ,'े' , 'नु' , 'दै' , 'ेको' , 'ै')
def stem_text_cat1(word):
    if word.endswith(suffixes):
        wordlist =  [word.rstrip(x) for x in suffixes]
        for i in wordlist:
            if i!= word:
                if i in allwords:
                    return i
                    
        
    return word
    

In [375]:
def stemming(text):
    text =  ' '.join([stem_text_cat1(a) for a in word_tokenize(text)])
    return ' '.join([stem_text_cat2(a) for a in word_tokenize(text)])
    


In [376]:
df['news'] = df['news'].map(stemming)

In [377]:
def sent_tokenize(text):
    sentence = [x for x in text.split('।')] 
    return sentence
df['news-ws']=df['news'].map(sent_tokenize)

In [378]:
def check(x):
    try:
        if isinstance(float(x), float):
            return False
    except:
        return True


In [379]:
# function to remove stopwords
def remove_stopword(sen):
    sen_new = " ".join([i for i in sen if i not in stopwords and check(i)])
    return sen_new
remove_stopwords = lambda sent : [remove_stopword(r.split()) for r in sent]


In [380]:
df['news-ws'] = df['news-ws'].map(remove_stopwords)

In [381]:
df['news-ws'][0]

['विश्व नम्वर वान टेक कम्पनी एप्पल निस प्रमुख र्यरी अधिकृत सिइओ पाउन तलब भत्ता चानचुने कुरै',
 'त्यसै एप्पल वर्तन सिइओ टिम कुक गत वर्ष सन् अर्ब रुपैयाँ बढि वाषिर्क तलबभत्ता बुझे',
 'अघिल्लो वर्ष तुलना सन् कुक तलब भत्ता प्रतिशत वृद्धि',
 'उन वर्ष एप्पल करोड डलर रकम बुझे',
 'कुक आधारभुत बेतन गत वर्ष प्रतिशत करोड रुपैयाँ वृद्धि नन इक्विटी इन्सेन्टिभ प्रतिशत वृद्धि करोड रुपैयाँ पुगे',
 'यतिधेरै तलब भत्ता थाप्न कुक एप्पल एकत्र कर्मचारी होलान् कर्मचारी तलब उन निक भन्न सोँच्नुहोला',
 'अचम्म एप्पल उच्च पदस्थ र्यरीमध्ये कुक पाए तलब भत्ता सबैभन्दा',
 'कम्पनी प्रमुख वित्तिय अधिकृत लू वाषिर्क तलब प्रतिशत वृद्धि उन गत वर्ष अढाइ अर्ब रुपैयाँ बढि तलब भत्ता बुझे',
 'रिटेल एण्ड अनलाइन स्टोर वरिष्ठ उपाध्यक्ष एन्जेला गत वर्ष एप्पल सबैभन्दा बढि तलब भत्ता बुझ्ने कर्मचारी',
 'उन गत वर्ष उन अर्ब करोड रुपैयाँ बढि तलब भत्ता बुझेकी छिन्',
 'गत वर्ष सन् एप्पलल बिक्रि प्रतिशत बढ्यो मुनाफा प्रतिशत बढे बताइए',
 'सन् यता एप्पलल शेयर मूल्य गिरावट',
 '']

In [382]:
from nltk import word_tokenize

In [383]:
vocab = set([x for x in ' '.join(df['news-ws'][2]).split(' ') ])
vocab = list(vocab)
vocab

['',
 'अर्',
 'क्यामरा',
 'प्रयोग',
 'तोकिए',
 'किटक्याट',
 'बाँकी',
 'दी',
 'सर्',
 'ओ',
 'सिगरेट',
 'नाम',
 'तलपटि्ट',
 'प्रेरित',
 'निर्ता',
 'अपरेटिंग',
 'भर्ज',
 'अलर्ट',
 'खाल',
 'सबैभन्दा',
 'वेपरकेड',
 'भन्न',
 'ल्याउन',
 'लिए',
 'ठिहा',
 'डलर',
 'सिस्टम',
 'तयार',
 'विश्व',
 'जस',
 'लत',
 'इ',
 'गराउँछ',
 'की',
 'बढ्न',
 'आइ',
 'रहे',
 'स्र्टफोन',
 'बनिरहे',
 'धुम्रपान',
 'विषय',
 'चुरोट',
 'निस',
 'लक्ष्य',
 'तपाइँ',
 'सिगार',
 'तय',
 'उपयोग',
 'आउन',
 'छोडाउन',
 'थि',
 'व्यापार',
 'गर्दछ',
 'सहयोगी',
 'छिटै',
 'प्लास्टिक',
 'कम्पनी',
 'ग्याजेट',
 'निक',
 'दिन्छ',
 'ब्याट्री',
 'पिउन',
 'प्वाल',
 'स्वाद',
 'त्र',
 'समयै',
 'वास्तव',
 'फिचर्स',
 'यहीँ',
 'अनौठो',
 'सक्नुहुन्छ',
 'महंगो',
 'रिपोर्ट',
 'जुपिटर',
 'सकिन्छ',
 'वासना',
 'फ्लासयुक्त',
 'मूल्य',
 'चलिरहे',
 'अमेरिकी',
 'क्रम',
 'चार्ज',
 'बढि',
 'बजार',
 'लिन',
 'ल्याए',
 'त्रै',
 'जी',
 'झोल',
 'मेलो',
 'धुमपान',
 'फोर',
 'फोन',
 'गरिरहे',
 'सकिनेछ',
 'त्याग्ने',
 'दाबी',
 'एप',
 'थ्री',
 'कफी',
 'भैसक्यो',
 'दुनिया

In [387]:
document = [checkNum((word_tokenize(x))) for x in df['kW-candidates'][2]]

In [388]:
from collections import OrderedDict
names = vocab
occurrences = OrderedDict((name, OrderedDict((name, 0) for name in names)) for name in names)

# Find the co-occurrences:
for l in document:
    for i in range(len(l)):
        for item in l[:i] + l[i + 1:]:
            occurrences[l[i]][item] += 1
'''
# Print the matrix:
print(' ', ' '.join(occurrences.keys()))
for name, values in occurrences.items():
    print(name, ' '.join(str(i) for i in values.values()))'''

"\n# Print the matrix:\nprint(' ', ' '.join(occurrences.keys()))\nfor name, values in occurrences.items():\n    print(name, ' '.join(str(i) for i in values.values()))"

In [389]:
rows = ['deg','freq','deg/freq']
word_scores = OrderedDict((name, OrderedDict((r, 0) for r in rows)) for name in names)

In [390]:
for key in word_scores.keys():
    word_scores[key]['deg'] = sum(occurrences[key].values())
    word_scores[key]['freq'] = len([x for x in occurrences[key].values() if x!=0])
    if word_scores[key]['freq']!=0:
        word_scores[key]['deg/freq'] = word_scores[key]['deg']/word_scores[key]['freq']
    else:
        word_scores[key]['deg/freq']= 0

In [391]:
word_scores

OrderedDict([('', OrderedDict([('deg', 0), ('freq', 0), ('deg/freq', 0)])),
             ('अर्',
              OrderedDict([('deg', 8),
                           ('freq', 7),
                           ('deg/freq', 1.1428571428571428)])),
             ('क्यामरा',
              OrderedDict([('deg', 3), ('freq', 3), ('deg/freq', 1.0)])),
             ('प्रयोग',
              OrderedDict([('deg', 2), ('freq', 2), ('deg/freq', 1.0)])),
             ('तोकिए',
              OrderedDict([('deg', 1), ('freq', 1), ('deg/freq', 1.0)])),
             ('किटक्याट',
              OrderedDict([('deg', 0), ('freq', 0), ('deg/freq', 0)])),
             ('बाँकी',
              OrderedDict([('deg', 1), ('freq', 1), ('deg/freq', 1.0)])),
             ('दी', OrderedDict([('deg', 2), ('freq', 2), ('deg/freq', 1.0)])),
             ('सर्',
              OrderedDict([('deg', 15),
                           ('freq', 14),
                           ('deg/freq', 1.0714285714285714)])),
             ('ओ', Ordere

In [307]:
def checkMe(x):
    try:
        if isinstance(float(x), float):
            return True
    except:
        return False


In [385]:
def findCandidates(text):
    clusters=[]
    word1=[]
    for word in word_tokenize(text):
        if (word in stopwords) or checkMe(word):
            clusters.append(word1)
            word1 =[]
            continue
        else:
            word1.append(word)
    return [' '.join(a).replace('।','') for a in clusters if len(a)>1]        

In [386]:
df['kW-candidates'] = df['news'].map(findCandidates)

In [392]:
# find word co-occurrence graph on candidate keywords 

In [393]:
df['kW-candidates'][2]

['समयै स्र्टफोन दुनिया अत्याधुनिक बनिरहे',
 'स्र्टफोन बजार आउन क्रम चलिरहे',
 ' यहीँ मेलो',
 'अमेरिकी कम्पनी निक अनौठो खाल स्र्टफोन बजार ल्याए',
 ' अमेरिकी कम्पनी वेपरकेड',
 'स्र्टफोन ल्याए',
 'जस तपाइँ फोन',
 'की चुरोट पिउन',
 'सक्नुहुन्छ  वास्तव',
 'ग्याजेट स्र्टफोन',
 'इ सिगरेट ठिहा रुप',
 ' धुम्रपान लत छोडाउन',
 'स्र्टफोन सहयोगी',
 'दाबी कम्पनी',
 ' दी भर्ज रिपोर्ट',
 'जुपिटर आइ ओ थ्री नाम',
 'स्र्टफोन विश्व इ सिगरेटयुक्त',
 'थ्री जी स्र्टफोन मूल्य',
 'डलर तोकिए',
 'अपरेटिंग सिस्टम रहे',
 'फोन हार्डवेयर फ्लासयुक्त क्यामरा',
 'ब्याट्री रहे',
 'ब्याट्री स्र्टफोन',
 'अर् इ सिगरेट',
 'ब्याट्री चार्ज सकिँदा अर् ब्याट्री उपयोग ल्याउन',
 'सकिन्छ  स्र्टफोन सबैभन्दा थि',
 'प्लास्टिक कभर रहे',
 'जस तलपटि्ट',
 'इ सिगरेट स्वाद लिन सकिनेछ ',
 'स्र्टफोन इ सिगरेट',
 'त्रै वेपरकेड एप रहे',
 ' जस ब्याट्री चार्ज',
 'इ चुरोट',
 'झोल बाँकी',
 'वासना रहे',
 'प्रयोग भैसक्यो भन्न',
 'विषय जानरी दिन्छ  स्र्टफोन निर्ता',
 'एप निस लक्ष्य तय',
 'धुमपान त्याग्ने ोतर्फ',
 'बढ्न प्रेरित गर्दछ  इ चुरोट बढि सर् ल

In [394]:
scoredCandidates = []
for sent in df['kW-candidates'][2]:
    sumis=0
    for word in word_tokenize(sent):
        sumis += word_scores[word]['deg/freq']
    scoredCandidates.append((sent,sumis/len(word_tokenize(sent))))

In [395]:
sorted(list(set(scoredCandidates)), key = lambda x : x[1],reverse=True)

[('इ चुरोट', 1.5),
 ('ब्याट्री स्र्टफोन', 1.4477124183006536),
 ('अर् इ सिगरेट', 1.4186507936507937),
 ('स्र्टफोन इ सिगरेट', 1.410247432306256),
 ('ब्याट्री रहे', 1.3888888888888888),
 (' जस ब्याट्री चार्ज', 1.3703703703703702),
 ('ब्याट्री चार्ज सकिँदा अर् ब्याट्री उपयोग ल्याउन', 1.365249433106576),
 ('इ सिगरेट ठिहा रुप', 1.2782738095238095),
 ('स्र्टफोन विश्व इ सिगरेटयुक्त', 1.2481617647058822),
 ('इ सिगरेट स्वाद लिन सकिनेछ ', 1.2226190476190477),
 ('बढ्न प्रेरित गर्दछ  इ चुरोट बढि सर् लिए एप अलर्ट गराउँछ वेपरकेड कम्पनी इ सिगरेट सिगार',
  1.198378110215378),
 (' अमेरिकी कम्पनी वेपरकेड', 1.145944741532977),
 ('स्र्टफोन ल्याए', 1.1302521008403361),
 ('अमेरिकी कम्पनी निक अनौठो खाल स्र्टफोन बजार ल्याए', 1.074848864370923),
 ('थ्री जी स्र्टफोन मूल्य', 1.0710784313725492),
 ('त्रै वेपरकेड एप रहे', 1.0704334365325079),
 ('दाबी कम्पनी', 1.0681818181818183),
 ('स्र्टफोन सहयोगी', 1.0588235294117647),
 ('ग्याजेट स्र्टफोन', 1.0588235294117647),
 ('डलर महंगो फोर जी स्र्टफोन', 1.0568627450980395),

In [398]:
stopwords = sorted(list( stopwords1 + ['हुँ' , 'गर्दछ','छिन्' , 'यता' , 'उन' ,'नआउन' , 'आउन' , 'यहीँ ','रहे' ,'नरहे' , 'जस' , 'सक्नुहुन्छ' ,'सक्नुहुन्न' ,'दिदैन' ,'गर्दैन' ,'नलिए', 'दिन्छ' , 'गर्दछ' , 'लिए' , 'हेर्न' , 'सकिने' ,'तपाइँ' ,'जुनसुकै']))

In [399]:
with open('listfile.txt', 'w') as filehandle:  
    for listitem in stopwords:
        filehandle.write('%s\n' % listitem)